export const events = [
  {
    id: 1,
    title: "Chicago Mixer",
    date: "May 15, 2026",
    city: "Chicago",
    venue: "The St. Regis Chicago",
    description: "Join professionals in downtown Chicago for an elegant evening of networking, conversation, and connection at The St. Regis Chicago.",
    time:"6:00 PM - 10:00 PM",
    dressCode: "The dress code for men and women is business professional",
    parking: "There is no parking on this property",
    dinner: "There is a vegiterian option and a nonvegiterian option",
  },
  {
    id: 2,
    title: "Los Angeles Mixer",
    date: "June 15, 2026",
    city: "Los Angeles",
    venue: "JW Marriott Los Angeles L.A. LIVE",
    description:  "Connect with professionals in the heart of downtown Los Angeles at L.A. LIVE, surrounded by the energy of the city’s entertainment district.",
    time:"6:00 PM - 10:00 PM",
    dressCode:"The dress code for men and women is business professional",
    parking: "There is valet parking for $30 please validate with reception to get half off",
    dinner: "There is a vegiterian option and a nonvegiterian option",
  },

  {
    id: 3,
    title: "New York Mixer",
    date: "June 18, 2026",
    city: "Los Angeles",
    venue: "W New York - Times Square",
    description:  "Meet and network with professionals in the center of Manhattan, steps away from the bright lights and fast-paced energy of Times Square.",
    time:"6:00 PM - 10:00 PM",
    dressCode:"The dress code for men and women is business professional",
    parking: "There is no parking on this property",
    dinner: "There is a vegiterian option and a nonvegiterian option",
  },

  {
    id: 4,
    title: "Madison Mixer",
    date: "June 20, 2026",
    city: "Los Angeles",
    venue: "AC Hotel Madison Downtown",
    description: "Enjoy a polished networking experience in downtown Madison with skyline views, modern hospitality, and meaningful professional conversations.",
    time:"6:00 PM - 10:00 PM",
    dressCode: "The dress code for men and women is business professional",
    parking: "There is valet parking for $30 please validate with reception to get half off",
    dinner: "There is a vegiterian option and a nonvegiterian option",
  },

  {
    id: 5,
    title: "Phoenix Mixer",
    date: "June 30, 2026",
    city: "Los Angeles",
    venue: "JW Marriott Phoenix Desert Ridge Resort & Spa",
    description:  "Network with professionals in a relaxed resort setting surrounded by desert views, upscale amenities, and a warm Phoenix atmosphere.",
    time:"6:00 PM - 10:00 PM",
    dressCode:"The dress code for men and women is business professional",
    parking: "There is no parking on this property",
    dinner: "There is a vegiterian option and a nonvegiterian option",
  },

  {
    id: 6,
    title: "San Francisco Mixer",
    date: "July 3, 2026",
    city: "Los Angeles",
    venue: "The Ritz-Carlton, San Francisco",
    description: "Build new connections in a refined San Francisco setting known for classic architecture, luxury hospitality, and a strong professional community.",
    time:"6:00 PM - 10:00 PM",
    dressCode:"The dress code for men and women is business professional",
    parking: "There is valet parking for $30 please validate with reception to get half off",
    dinner: "There is a vegiterian option and a nonvegiterian option",
  },

  {
    id: 7,
    title: "Miami Mixer",
    date: "July 8, 2026",
    city: "Los Angeles",
    venue: "The St. Regis Bal Harbour Resort",
    description: "Join an upscale networking evening near Miami’s coastline, combining professional connection with the luxury atmosphere of Bal Harbour.",
    time:"6:00 PM - 10:00 PM",
    dressCode:"The dress code for men and women is business professional",
    parking: "There is no parking on this property",
    dinner: "There is a vegiterian option and a nonvegiterian option",
  },

  {
    id: 8,
    title: "Fort Lauderdale Mixer",
    date: "August 10, 2026",
    city: "Los Angeles",
    venue: "The St. Regis Resort & Residences Bahia Mar, Fort Lauderdale",
    description: "Connect with professionals in Fort Lauderdale at an upscale waterfront-inspired venue designed for meaningful networking and conversation.",
    time:"6:00 PM - 10:00 PM",
    dressCode: "The dress code for men and women is business professional",
    parking: "There is valet parking for $30 please validate with reception to get half off",
    dinner: "There is a vegiterian option and a nonvegiterian option",
  },
];